{% set name = "core-js" %}
{% set version = "2.6.9" %}
{% set sha256 = "0fc2269e1b2110d423c3cf7200f37e27e82c302c447ce8e941d7453609930a9d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zloirock/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g core-js
  requires:
    - nodejs
   

about:
  home: https://github.com/zloirock/core-js
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Modular standard library for JavaScript'
  description: |
    Modular standard library for JavaScript
  doc_url: https://github.com/zloirock/core-js
  dev_url: https://github.com/zloirock/core-js

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
