{% set name = "core-js" %}
{% set version = "3.6.5" %}
{% set sha256 = "42ebf44ebf31018f96ec7d5f1fcc544b9030d340df0a73fcd836b67c2c763543" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zloirock/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g core-js
  requires:
    - nodejs


about:
  home: https://github.com/zloirock/core-js
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modular standard library for JavaScript
  description: |
    Modular standard library for JavaScript
  doc_url: https://github.com/zloirock/core-js
  dev_url: https://github.com/zloirock/core-js
