{% set name = "core-js" %}
{% set version = "2.5.5" %}
{% set sha256 = "d7767a27bcd694d103bacab6c9b60096488b4debe880c1312a16df418ef3a77a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zloirock/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g core-js
  requires:
    - nodejs
   

about:
  home: https://github.com/zloirock/core-js
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Modular standard library for JavaScript'
  description: |
    Modular standard library for JavaScript
  doc_url: https://github.com/zloirock/core-js
  dev_url: https://github.com/zloirock/core-js

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
