{% set name = "core-js" %}
{% set version = "2.6.11" %}
{% set sha256 = "4915740ec09919630c60148b34bfd97cf48d513e77a8a937ecd2b3d49516f61a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zloirock/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g core-js
  requires:
    - nodejs
   

about:
  home: https://github.com/zloirock/core-js
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Modular standard library for JavaScript'
  description: |
    Modular standard library for JavaScript
  doc_url: https://github.com/zloirock/core-js
  dev_url: https://github.com/zloirock/core-js

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
