{% set name = "core-js" %}
{% set version = "2.5.3" %}
{% set sha256 = "bd4ab20fcaa132a93d662cec91447f0b10994aaca66974c7abaf702d38d997b8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zloirock/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g core-js
  requires:
    - nodejs
   

about:
  home: https://github.com/zloirock/core-js
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Modular standard library for JavaScript'
  description: |
    Modular standard library for JavaScript
  doc_url: https://github.com/zloirock/core-js
  dev_url: https://github.com/zloirock/core-js

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
