travis:
  secure:
    BINSTAR_TOKEN: DpHUD/S5nEVJGz+xFw1/5RRJCnviBZEIF2fO4jelD7R8llIeMTqyO9FlghlDgCcbTYpXoX9AzD0RtwzXZeZCdvVRvom6NyYBZ4kUwlsYfyxvxM8sin08jBOZa8FGtuxK4GGLNSzeuIw5Tpmxh3T8P119XoYq0qRyhgSgnavUaOKXYj8X2s8QCGRGtJFJIismLIooRhEgg61EWfT8iYwKFqQAQpDRKR+daHVmxkyVIz/Ucr2Jd8a9N0KrP0+du8XlRWEHnakUJtPm5GzGwnktF+sm09qrUU7Mvmm6PoASTaSx15cH7o+/sWPdaxHX9XOeTwY657NGJ0Te7BIDBuhCvRxCO9lLbAjvHXWahA0JX+93m415uT2STbXU6fKTzaDVjvAVA0NmjWNLidyyIw1drVkhQlOjgacBqVVciK46ZD5bIpzBU1yTMvZ3hi34aUEnDnd43HSiQW63eFGtCxFROfh3hREUppBPzdR4ZTkkCNjUOl8pEcXTYiM+CK+HvkiXHqTNqM6h3yivHgLrKK7fLEf2jIFZXcGPEXkXKUH/JiArmQAjOgXdB6v7Pkq6KLWqrmwQiFl8NHQ+PBaiFfOZLccvW6ReNcnoWrLUuYyvFVn8sdMHJwrdgQTQF0NS+f6htiyBRTGuc55v49yVFnD7N3jscr+54/vveOlD+TuhxPA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
