travis:
  secure:
    BINSTAR_TOKEN: EF76YSPvL7Ni/ifU20/teb6FsiSmn9NmKmpZKZuhqQOh0T6bdqG2P0EkTgozlpt12a0z396I3m0IPi8n8uNTbUy+e09vwDylIyBlLWpVlmCGPJ8bXaBpHCJulVElmxg/XtNsh11AuxyAGmUnBZWAybgy0anADrv2Us95lw+K9LP8TRNli8y1mJG6sLW31s/RY+tX2Hab3xHksIdqgMRLt9O+DW9TT1mpyT4vDBj0t+zc9UOziOeLwa5pUYHFYbebjeg8B7XITFb7oreviIJzC3go/RN5V0XZ6lKXWkpm4VTofwiKAY6L/XujuSVr3YVyTZE4ia8v/SfLX0LkU/KoULj0QbDHmRepUfrgWz7oeBF7MDM2kk4/wZficDChRQZi0/qrInkIuzNpJnQ+w1UDpbNeCnWFmg7pk/L/+4AA8ZTojN7CM++S9EPn82a08l3xVseehBHLNDGEKQbZo9kn22YEoe7lAEQJ4KvltvRW9S/L4nf/0xH8/I3cCMn2+mxWXjxWNEyIPGyUmAbuVtRlEUCLb20zrAPAlNCYqOrPaKf1goS+Z6yydhdd4oH30Smg6TZHCauYzQmNNqmTIH+egtk6r6jdF4x1TWNsy6AV/SpPeIaeUFcuAr8KH0/ikvNW3VeYHA+nAFBEsKrhlqk+Wqk+FFUPcWss4nRMhd2B8zw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
